#!/usr/bin/env python
"""Generates a REINVENT4 staged_learning TOML config.

A generation script rather than a hand-written TOML file because the novelty
(TanimotoSimilarity) component's reference set is 500 SMILES sampled from the
LINCS library (reinvent_run/configs/novelty_reference_smiles.txt) -- too large
to maintain by hand without risking a transcription error (exactly what broke
the positive-control SMILES earlier in this project).

Reward function per AGENTS.md Section 6:
  Oracle (SenmayoBridge)                    weight 0.5
  QED (drug-likeness)                       weight 0.2
  Novelty (Tanimoto distance from library)  weight 0.15
  Synthesizability (SAScore)                weight 0.15

Usage: generate_staged_learning_toml.py [pilot|production]
  pilot (default): fresh agent from the prior, 300 steps, batch 64.
  production: continues from the pilot's stage1.chkpt, batch 128, more steps.
"""
import json
import os
import sys

MODE = sys.argv[1] if len(sys.argv) > 1 else "pilot"
assert MODE in ("pilot", "production", "run2"), f"unknown mode {MODE}"

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RUN = f"{ROOT}/reinvent_run"

with open(f"{RUN}/configs/novelty_reference_smiles.txt") as f:
    ref_smiles = [l.strip() for l in f if l.strip()]

# json.dumps escapes backslashes/quotes the same way TOML basic strings require --
# SMILES routinely contain '\' (e.g. '/C=C\') which broke a naive f'"{s}"' quoting.
ref_smiles_toml = ",\n    ".join(json.dumps(s) for s in ref_smiles)

CUSTOM_ALERTS_SMARTS = [
    "[*;r8]", "[*;r9]", "[*;r10]", "[*;r11]", "[*;r12]", "[*;r13]", "[*;r14]",
    "[*;r15]", "[*;r16]", "[*;r17]",
    "[#8][#8]", "[#6;+]", "[#16][#16]", "[#7;!n][S;!$(S(=O)=O)]",
    "[#7;!n][#7;!n]", "C#C", "C(=[O,S])[O,S]",
]
custom_alerts_toml = ",\n    ".join(json.dumps(s) for s in CUSTOM_ALERTS_SMARTS)

if MODE == "pilot":
    agent_file = f"{RUN}/priors/reinvent_pubchem.prior"
    use_checkpoint = "false"
    batch_size = 64
    chkpt_file = f"{RUN}/outputs/stage1.chkpt"
    summary_csv_prefix = f"{RUN}/outputs/staged_learning"
    max_score = 0.6
    min_steps = 50
    max_steps = 300
    out_name = "staged_learning.toml"
    df_type = "IdenticalMurckoScaffold"
    df_bucket_size = 25
    df_minsimilarity_line = ""
    sigma = 128
elif MODE == "production":
    # Continue the pilot's already-learned agent (mean score 0.36, rising) rather
    # than restarting from the raw prior -- use_checkpoint=true also carries over
    # the diversity filter's scaffold memory so the same scaffolds aren't re-explored.
    agent_file = f"{RUN}/outputs/stage1.chkpt"
    use_checkpoint = "true"
    batch_size = 128
    chkpt_file = f"{RUN}/outputs/production_stage1.chkpt"
    summary_csv_prefix = f"{RUN}/outputs/production"
    max_score = 0.75
    min_steps = 200
    max_steps = 3000
    out_name = "staged_learning_production.toml"
    df_type = "IdenticalMurckoScaffold"
    df_bucket_size = 25
    df_minsimilarity_line = ""
    sigma = 128
else:  # run2
    # Run 1 (pilot->production) collapsed: 57% of the converged set shared one bare
    # phenyl Murcko scaffold, and IdenticalMurckoScaffold's exact-match bucket
    # (25/scaffold) only zeroed ~10% of its instances instead of the near-100%
    # the mechanism should give once a bucket is over quota -- diagnosed via
    # reinvent_run/outputs/run1_archive + data/processed/run1 (see analysis).
    # First attempt at a fix used ScaffoldSimilarity, but that component has a
    # real bug in this REINVENT4 version: it crashes (GetAtomPairFingerprint on
    # a None mol) whenever a generated molecule has no ring system at all (empty
    # Murcko scaffold), which happens routinely with an unconverged agent -- not
    # usable. Back to IdenticalMurckoScaffold, but with a much smaller bucket (5
    # instead of 25) so the cap bites much earlier, fresh restart from the raw
    # prior (not the already-collapsed run-1 agent), and reduced sigma so DAP
    # updates are less aggressively exploitative.
    agent_file = f"{RUN}/priors/reinvent_pubchem.prior"
    use_checkpoint = "false"
    batch_size = 128
    chkpt_file = f"{RUN}/outputs/run2_stage1.chkpt"
    summary_csv_prefix = f"{RUN}/outputs/run2"
    max_score = 0.75
    min_steps = 200
    max_steps = 3000
    out_name = "staged_learning_run2.toml"
    df_type = "IdenticalMurckoScaffold"
    df_bucket_size = 5
    df_minsimilarity_line = ""
    sigma = 100

toml_content = f'''# Plan B staged_learning (RL) config -- generated by
# reinvent_run/scripts/generate_staged_learning_toml.py {MODE}, do not
# hand-edit the novelty reference list, regenerate instead.
#
# Reward function per AGENTS.md Section 6: SenmayoBridge oracle (0.5) + QED
# drug-likeness (0.2) + novelty vs LINCS library (0.15) + SAScore
# synthesizability (0.15), geometric mean.

run_type = "staged_learning"
device = "cuda:0"
tb_logdir = "tb_logs_{MODE}"
json_out_config = "{RUN}/outputs/_staged_learning_{MODE}.json"

[parameters]
summary_csv_prefix = "{summary_csv_prefix}"
use_checkpoint = {use_checkpoint}
purge_memories = false
prior_file = "{RUN}/priors/reinvent_pubchem.prior"
agent_file = "{agent_file}"
batch_size = {batch_size}
randomize_smiles = true

[learning_strategy]
type = "dap"
sigma = {sigma}
rate = 0.0001

[diversity_filter]
type = "{df_type}"
bucket_size = {df_bucket_size}{df_minsimilarity_line}
minscore = 0.4

[[stage]]
chkpt_file = "{chkpt_file}"
termination = "simple"
max_score = {max_score}
min_steps = {min_steps}
max_steps = {max_steps}

[stage.scoring]
type = "geometric_mean"

# -- structural alert filter (applied before aggregation, no weight) --
[[stage.scoring.component]]
[stage.scoring.component.custom_alerts]
[[stage.scoring.component.custom_alerts.endpoint]]
name = "Unwanted SMARTS"
params.smarts = [
    {custom_alerts_toml}
]

# -- main biological objective: SenMayo reversal (Plan B bridge model) --
[[stage.scoring.component]]
[stage.scoring.component.SenmayoBridge]
[[stage.scoring.component.SenmayoBridge.endpoint]]
name = "SenMayo_reversal"
weight = 0.5
params.model_file = "{ROOT}/data/processed/bridge_model.joblib"
transform.type = "sigmoid"
transform.low = -1.0
transform.high = 2.5
transform.k = 0.5

# -- drug-likeness --
[[stage.scoring.component]]
[stage.scoring.component.QED]
[[stage.scoring.component.QED.endpoint]]
name = "QED"
weight = 0.2

# -- novelty: reward LOW similarity to the LINCS training library --
[[stage.scoring.component]]
[stage.scoring.component.TanimotoSimilarity]
[[stage.scoring.component.TanimotoSimilarity.endpoint]]
name = "Novelty_vs_LINCS"
weight = 0.15
params.smiles = [
    {ref_smiles_toml}
]
params.radius = 3
params.use_counts = true
params.use_features = true
transform.type = "reverse_sigmoid"
transform.low = 0.0
transform.high = 0.5
transform.k = 0.5

# -- synthesizability filter (Ertl SAScore, 1=easy .. 10=hard) --
[[stage.scoring.component]]
[stage.scoring.component.SAScore]
[[stage.scoring.component.SAScore.endpoint]]
name = "Synthesizability"
weight = 0.15
transform.type = "reverse_sigmoid"
transform.low = 2.0
transform.high = 6.0
transform.k = 0.5
'''

out_path = f"{RUN}/configs/{out_name}"
with open(out_path, "w") as f:
    f.write(toml_content)
print(f"Wrote {out_path} ({len(toml_content)} bytes, {len(ref_smiles)} novelty reference SMILES)")
